create table public.tarea_test (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  nombre text null,
  completada boolean null,
  constraint tarea_test_pkey primary key (id)
) TABLESPACE pg_default;
